






































































    assert all(r["processed"] for r in results)    assert len(results) == 3        )        run_workflow()        run_workflow(),        run_workflow(),    results = await asyncio.gather(    # Run multiple workflows concurrently            return await graph.execute({"input": "test"})        graph.set_entrypoint("processor")        graph.add_node("processor", processor)        processor = ProcessingNode()        graph = LangChainGraph()    async def run_workflow():    """Test executing multiple workflows in parallel."""async def test_parallel_execution():@pytest.mark.asyncio@pytest.mark.integration        await graph.execute({"input": "test"})    with pytest.raises(ValueError, match="Test error"):        graph.set_entrypoint("error")    graph.add_node("error", ErrorNode())                raise ValueError("Test error")        async def invoke(self, state):    class ErrorNode(ProcessingNode):        graph = LangChainGraph()    """Test error handling in the workflow."""async def test_error_handling():@pytest.mark.asyncio@pytest.mark.integration    assert "input" in result    assert result["completed"]    assert result["processed"]    # Verify flow        result = await graph.execute(initial_state)    initial_state = {"input": "test data"}    # Execute        graph.add_edge("processor", "finalizer")    graph.set_entrypoint("processor")    graph.add_node("finalizer", finalizer)    graph.add_node("processor", processor)    # Build graph        finalizer = FinalNode(chain_type="finalizer", model_name="test")    processor = ProcessingNode(chain_type="processor", model_name="test")    # Create nodes        graph = LangChainGraph()    """Test a complete workflow with multiple nodes and state transitions."""async def test_full_workflow():@pytest.mark.asyncio@pytest.mark.integration    # ...existing code...    model_config = ConfigDict(arbitrary_types_allowed=True)class BaseLangChainNode(BaseModel):from pydantic import BaseModel, ConfigDictimport asynciofrom valthera_langchain.nodes import ProcessingNode, FinalNodefrom valthera_langchain.graph import LangChainGraphimport pytest