[pytest]
markers =
    integration: marks tests as integration tests
asyncio_mode = auto
filterwarnings =
    ignore:Failing to pass a value to the 'type_params' parameter of 'typing.ForwardRef._evaluate' is deprecated:DeprecationWarning
