version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  jarvis:
    build:
      context: .
      dockerfile: Dockerfile
    image: valthera/jarvis:local
    restart: always
    environment:
      - JARVIS_HTTP_PORT=8001
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    logging: *default-logging
