version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  jarvis-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: valthera/jarvis-api:local
    restart: always
    environment:
      - JARVIS_HTTP_PORT=8001
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    logging: *default-logging
    networks:
      - jarvis-network

  jarvis-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: valthera/jarvis-web:local
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - jarvis-api
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging: *default-logging
    networks:
      - jarvis-network

networks:
  jarvis-network:
    driver: bridge
