from abc import ABC, abstractmethod
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from valthera_core.core.prompt import Prompt
from valthera_core.core.tool import Tool


class AgentResponse(BaseModel):
    """Represents an agent’s response to a given prompt."""
    
    response_text: str   # The textual response generated by the agent
    metadata: Optional[Dict[str, Any]] = None  # Optional metadata (e.g., confidence score, timestamps)
    tools_used: Optional[List[str]] = None  # Track tools used (if any)

    class Config:
        """Pydantic config for additional settings."""
        allow_mutation = False  # Ensures immutability for safety


class Agent(ABC):
    @abstractmethod
    def handle_prompt(self, prompt: Prompt) -> AgentResponse:
        pass

    @abstractmethod
    def register_tool(self, tool: Tool) -> None:
        pass