"""
Developer Documentation: Agent Base Class

This module defines the `Agent` base class and the `AgentResponse` model, which form the foundation of AI-driven agents 
in the `valthera_core` framework. It provides an abstract interface for implementing agents that process prompts 
and interact with registered tools.

## Classes

### AgentResponse (Pydantic Model)
Represents the structured response from an agent.

#### Attributes:
- `response_text` (str): The textual response generated by the agent.
- `metadata` (Optional[Dict[str, Any]]): Additional metadata, such as confidence scores or timestamps. Default is `None`.
- `tools_used` (Optional[List[str]]): A list of tool names that were utilized during response generation. Default is `None`.

#### Configuration:
- `allow_mutation = False`: Ensures immutability for safety.

### Agent (Abstract Base Class)
Defines the interface for all AI agents. Subclasses must implement methods to handle prompts and register tools.

#### Methods:
- `handle_prompt(self, prompt: Prompt) -> AgentResponse`
  - **Description**: Processes a given `Prompt` and returns an `AgentResponse`.
  - **Parameters**:
    - `prompt` (Prompt): The input prompt object containing user input.
  - **Returns**:
    - `AgentResponse`: The structured response, including generated text, metadata, and tool usage.
  - **Raises**:
    - `NotImplementedError`: If not implemented in a subclass.

- `register_tool(self, tool: Tool) -> None`
  - **Description**: Registers a tool that the agent can use when processing prompts.
  - **Parameters**:
    - `tool` (Tool): The tool instance to be registered.
  - **Returns**: None
  - **Raises**:
    - `NotImplementedError`: If not implemented in a subclass.
"""

from abc import ABC, abstractmethod
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from valthera_core.core.prompt import Prompt
from valthera_core.core.tool import Tool


class AgentResponse(BaseModel):
    """
    Represents a structured response generated by an AI agent in response to a given prompt.

    Attributes:
        response_text (str): The text response generated by the agent.
        metadata (Optional[Dict[str, Any]]): Additional metadata, such as confidence scores or timestamps.
        tools_used (Optional[List[str]]): A list of tool names that were utilized, if applicable.
    """

    response_text: str
    metadata: Optional[Dict[str, Any]] = None
    tools_used: Optional[List[str]] = None

    class Config:
        """Pydantic model configuration to enforce immutability."""
        allow_mutation = False


class Agent(ABC):
    """
    Abstract base class for AI agents that process prompts and interact with tools.

    Subclasses must implement methods for handling prompts and registering tools.
    """

    @abstractmethod
    def handle_prompt(self, prompt: Prompt) -> AgentResponse:
        """
        Processes a given prompt and returns an agent-generated response.

        Args:
            prompt (Prompt): The input prompt containing user-provided data.

        Returns:
            AgentResponse: A structured response containing the generated text, metadata, and tools used.

        Raises:
            NotImplementedError: If the method is not implemented in a subclass.
        """
        pass

    @abstractmethod
    def register_tool(self, tool: Tool) -> None:
        """
        Registers a tool that the agent can utilize during prompt processing.

        Args:
            tool (Tool): The tool instance to be registered.

        Raises:
            NotImplementedError: If the method is not implemented in a subclass.
        """
        pass
