"""
Developer Documentation: Tool Base Class

This module defines the `Tool` abstract base class used in the `valthera_core` framework.
It provides a common interface for tools that can be utilized by AI agents.

## Classes

### Tool (Abstract Base Class)
Represents a generic tool that an AI agent can use.

#### Attributes:
- `name` (str): A unique identifier for the tool.
- `description` (str): A human-readable description of the tool's functionality.

#### Methods:
- `run(self, input_data: Dict[str, Any]) -> Dict[str, Any]`
  - **Description**: Executes the tool based on provided input data.
  - **Parameters**:
    - `input_data` (Dict[str, Any]): The input required for the tool to function.
  - **Returns**:
    - `Dict[str, Any]`: The processed output generated by the tool.
  - **Raises**:
    - `NotImplementedError`: If not implemented in a subclass.

#### Configuration:
- `allow_mutation = False`: Ensures immutability, preventing modification after initialization.

"""

from abc import ABC, abstractmethod
from pydantic import BaseModel
from typing import Dict, Any


class Tool(ABC, BaseModel):
    """
    Abstract base class for tools that agents can utilize.

    Attributes:
        name (str): A unique identifier for the tool.
        description (str): A human-readable description of the tool's purpose.
    """

    name: str
    description: str

    @abstractmethod
    def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes the tool using the provided input data.

        Args:
            input_data (Dict[str, Any]): Input parameters required for tool execution.

        Returns:
            Dict[str, Any]: The result produced by the tool after execution.

        Raises:
            NotImplementedError: If the method is not implemented in a subclass.
        """
        pass

    class Config:
        """Pydantic model configuration to enforce immutability."""
        allow_mutation = False
